### PR TITLE
update IntellJ IDEA status

### PR DESCRIPTION
**Pull request by matklad**
We do support syntax checking out of the box :)

### CODE REVIEW

**Comment by contradictioned** [comment]
Great to hear that and thanks for the change :+1:

**Comment by matklad** [comment]
Hm, wait a moment, what exactly `supported via plugin` means? 

Our intelliJ plugin checks syntax without `racer` and `rustc`, that's why I said it is "out of the box". But our plugin is not bundled with IDEA, you have to install it yourself. Should I add `<sup>1</sup>` thing then?

**Comment by contradictioned** [comment]
Oh ok, then the superscript-1 is missing. But as I am working on it anyway, I am adding it ;)

Just to make sure, you are refering to https://github.com/intellij-rust/intellij-rust this?

"Out-of-the-box" means, if you just install the editor/IDE, this particular feature is supported.
It's somehow a measure for the presence of Rust.

**Comment by matklad** [comment]
>Just to make sure, you are refering to https://github.com/intellij-rust/intellij-rust this?

Yep, we moved the repo to github organization couple of days ago, you can change URL in index.jade :)

>"Out-of-the-box" means, if you just install the editor/IDE, this particular feature is supported.

In this case you shoud add superscripts for both syntax highlighting and syntax checking for intelliJ Rust.

**Pull request merged**
