### PR TITLE
Textadept added to table.jade

### PR DESCRIPTION
**Pull request by abaez**
Here is a Textadept addition into table.jade. Not sure if you like to do the addition yourself. It's why I didn't add the commit a few days ago into the previous PR. Sort of forgot about it until today. Anyway, doing the PR now, just to help out. 

Also, thank you for accepting the previous Pull Request. :+1:

### CODE REVIEW

**Comment by contradictioned** [comment]
I noticed it and started to make some thoughts about "too many editors in the table".
But I don't mind adding it (yet -- if we get into [this](https://en.wikipedia.org/wiki/List_of_text_editors) dimensions, I have to reconsider),

thanks for the PR ;)

**Comment by abaez** [comment]
Considering the *tiny* list for lua[1], I think it will eventually
become the “too many editors in the table” problem. Sort of a nice
problem to have I think, but an annoying one for sure on listing.


On Sat, Oct 17, 2015, at 07:10 AM, Manuel Hoffmann wrote:







> I noticed it and started to make some thoughts about "too many editors
> in the table".
>
But I don't mind adding it (yet -- if we get into this[2] dimensions, I
have to reconsider),


> thanks for the PR ;)




> — Reply to this email directly or view it on GitHub[3].


>







Links:

  1. http://lua-users.org/wiki/LuaEditorSupport
  2. https://en.wikipedia.org/wiki/List_of_text_editors
  3. https://github.com/contradictioned/areweideyet/pull/12#issuecomment-148907799

**Comment by contradictioned** [comment]
Another thing: this `ta-rust` plugin needs racer for autocompletion and goto-definition?

**Comment by abaez** [comment]
> Another thing: this ta-rust plugin needs racer for autocompletion and
> goto-definition?






Not at all.  I actually wrote the abilities myself before racer was
around or functional.  Goto comes from the ctags[1] module and auto
complete comes from the internal built reference in the ta-rust plugin.
I am currently writing a racer version to use it as well, for the task.
Also, while not always completely accurate, the ctrl+h shortcut gives
the reference of a rust type/method if under cursor when pressed. The
Readme.md[2] tries to explain all the abilities of the module for
Textadept. Though I should take time to update the Readme easier
comprehension…



Links:

  1. http://foicica.com/hg/ctags/
  2. https://bitbucket.org/a_baez/ta-rust/src/020e50d8a594fa52b2a7325ce64cfb874883d65e/README.md?at=default

**Comment by contradictioned** [comment]
Ah okay, this is why it is filed under TODO.
Nice work btw, I just now realized that you are the author of that plugin ;)

**Pull request merged**
